todoapp:
  site:
    author: SungA Cho
    description: What're your plans today?
  data:
    initialize: true

Exception:
  TodoNotFoundException: 요청한 할 일을 찾을 수 없어요.

spring:
  application:
    name: todo

logging:
  level:
    '[todoapp]': debug # 로거 이름을 명시적으로 [todoapp]으로 지정했을 때 적용
    web: trace # 패키지 기반으로 설정
    sql: debug

# 서버 인코딩 설정
server:
  # 오류 설정 전략 변경
  error:
    include-message: always #오류 발생시 메세지 포함
    include-binding-errors: always
  servlet:
    encoding:
      charset: utf-8
      force: true